service: codebuild

provider:
  name: aws
  stage: ${opt:stage,'dev'}
  region: eu-west-1

resources:
  Resources:
    BuildRoleSecure:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: BuildRoleSecure
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - codebuild.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: BuildRoleSecure
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: "*"
                  Resource: "*"

    Project:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: myProjectName
        ServiceRole: !GetAtt BuildRoleSecure.Arn
        Artifacts:
          Type: no_artifacts
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:4.0
          EnvironmentVariables:
            - Name: varName
              Value: varValue
        Source:
          Location: https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/freedat-ss
          Type: CODECOMMIT
        TimeoutInMinutes: 10
